name: flutter_tts
description: A Flutter plugin for Text-To-Speech on iOS and Android.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tundralabs.fluttertts
        pluginClass: FlutterTtsPlugin
      ios:
        pluginClass: FlutterTtsPlugin

dependencies:
  flutter:
    sdk: flutter
